version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: direct
    groups:
      python-packages:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit-hooks:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-images:
        patterns:
          - "*"
