"""Pydantic request/response schemas for lifecycle endpoints.

Split from the former monolithic ``schemas.py`` into one module per API
domain. This package re-exports every model so that existing
``from ...lifecycle.schemas import X`` imports keep working unchanged.
"""

from __future__ import annotations

from robotsix_central_deploy.lifecycle.schemas._base import (
    _DeployResultBase,
    _EnvSecretsFields,
    _JobStatusFields,
)
from robotsix_central_deploy.lifecycle.schemas.chat_agent import (
    ChatAgentAuditEntryResponse,
    ChatAgentAuditLogResponse,
    ChatAgentConfigRollbackResponse,
    ChatAgentDeployRequest,
    ChatAgentDeployResponse,
    ChatAgentDiskReclaimRequest,
    ChatAgentDiskReclaimResponse,
    ChatAgentEnvResponse,
    ChatAgentEnvUpdate,
    ChatAgentMutationDisableResponse,
    ChatAgentMutationEnableRequest,
    ChatAgentMutationEnableResponse,
    ChatAgentPreviewDeployRequest,
    ChatAgentPreviewDeployResponse,
    ChatAgentPreviewTeardownResponse,
    ChatAgentRegisterRequest,
    ChatAgentRegisterResponse,
    ChatAgentRestartResponse,
    ChatAgentSelfRestartResponse,
    ChatAgentSelfUpdateResponse,
    ChatAgentServiceDeployResponse,
    ChatAgentTestDeployRequest,
    ChatAgentTestDeployResponse,
    ChatAgentUpdateResponse,
)
from robotsix_central_deploy.lifecycle.schemas.claude_auth import (
    ClaudeAuthCancelRequest,
    ClaudeAuthCompleteRequest,
    ClaudeAuthCompleteResponse,
    ClaudeAuthCredentialsRequest,
    ClaudeAuthCredentialsResponse,
    ClaudeAuthLoginResponse,
    ClaudeAuthStatusResponse,
)
from robotsix_central_deploy.lifecycle.schemas.config import (
    ComponentSuggestItem,
    ComponentSuggestResponse,
    ConfigExportResponse,
    ConfigResponse,
    ContractRefreshRequest,
    ContractRefreshResponse,
    SelfConfigResponse,
    SelfConfigRollbackRequest,
    SelfConfigVersion,
    SelfConfigVersionsResponse,
    SelfConfigWriteResponse,
)
from robotsix_central_deploy.lifecycle.schemas.deploy import (
    DeployAcceptedResponse,
    DeployJobStatusResponse,
)
from robotsix_central_deploy.lifecycle.schemas.diagnose import (
    DiagnoseEdgeProbe,
    DiagnoseRepoContract,
    DiagnoseReport,
    DiagnoseRouting,
    DiagnoseRuntime,
    DiagnoseStoredSpec,
    DiagnoseVerdict,
)
from robotsix_central_deploy.lifecycle.schemas.env import (
    EnvResponse,
    EnvSyncResponse,
    EnvUpdate,
)
from robotsix_central_deploy.lifecycle.schemas.onboard import (
    OnboardConfirmAcceptedResponse,
    OnboardConfirmRequest,
    OnboardJobStatusResponse,
    OnboardPreflightRequest,
    OnboardPreflightResponse,
    PortShift,
)
from robotsix_central_deploy.lifecycle.schemas.volume import (
    OrphanVolume,
    OrphanVolumesResponse,
    PruneVolumesRequest,
    PruneVolumesResponse,
    RelocateVolumeRequest,
    RelocateVolumeResponse,
    VolumeEntry,
    VolumeFileResponse,
    VolumeFileWriteRequest,
    VolumeFileWriteResponse,
    VolumeListResponse,
)

__all__ = [
    "ChatAgentAuditEntryResponse",
    "ChatAgentAuditLogResponse",
    "ChatAgentConfigRollbackResponse",
    "ChatAgentDeployRequest",
    "ChatAgentDeployResponse",
    "ChatAgentDiskReclaimRequest",
    "ChatAgentDiskReclaimResponse",
    "ChatAgentEnvResponse",
    "ChatAgentEnvUpdate",
    "ChatAgentMutationDisableResponse",
    "ChatAgentMutationEnableRequest",
    "ChatAgentMutationEnableResponse",
    "ChatAgentPreviewDeployRequest",
    "ChatAgentPreviewDeployResponse",
    "ChatAgentPreviewTeardownResponse",
    "ChatAgentRegisterRequest",
    "ChatAgentRegisterResponse",
    "ChatAgentRestartResponse",
    "ChatAgentSelfRestartResponse",
    "ChatAgentSelfUpdateResponse",
    "ChatAgentServiceDeployResponse",
    "ChatAgentTestDeployRequest",
    "ChatAgentTestDeployResponse",
    "ChatAgentUpdateResponse",
    "ClaudeAuthCancelRequest",
    "ClaudeAuthCompleteRequest",
    "ClaudeAuthCompleteResponse",
    "ClaudeAuthCredentialsRequest",
    "ClaudeAuthCredentialsResponse",
    "ClaudeAuthLoginResponse",
    "ClaudeAuthStatusResponse",
    "ComponentSuggestItem",
    "ComponentSuggestResponse",
    "ConfigExportResponse",
    "ConfigResponse",
    "ContractRefreshRequest",
    "ContractRefreshResponse",
    "DeployAcceptedResponse",
    "DeployJobStatusResponse",
    "DiagnoseEdgeProbe",
    "DiagnoseRepoContract",
    "DiagnoseReport",
    "DiagnoseRouting",
    "DiagnoseRuntime",
    "DiagnoseStoredSpec",
    "DiagnoseVerdict",
    "EnvResponse",
    "EnvSyncResponse",
    "EnvUpdate",
    "OnboardConfirmAcceptedResponse",
    "OnboardConfirmRequest",
    "OnboardJobStatusResponse",
    "OnboardPreflightRequest",
    "OnboardPreflightResponse",
    "OrphanVolume",
    "OrphanVolumesResponse",
    "PortShift",
    "PruneVolumesRequest",
    "PruneVolumesResponse",
    "RelocateVolumeRequest",
    "RelocateVolumeResponse",
    "SelfConfigResponse",
    "SelfConfigRollbackRequest",
    "SelfConfigVersion",
    "SelfConfigVersionsResponse",
    "SelfConfigWriteResponse",
    "VolumeEntry",
    "VolumeFileResponse",
    "VolumeFileWriteRequest",
    "VolumeFileWriteResponse",
    "VolumeListResponse",
    "_DeployResultBase",
    "_EnvSecretsFields",
    "_JobStatusFields",
]
