name: Lint Workflows

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-workflows:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@188518bece972d7d5f1c4e2a0f2226d2526dc0fa  # main
    with:
      run-actionlint: true
      run-zizmor: true
